version: "3.9"
services:
  web:
    build:
      context: "node-services"
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
      - "9209:9209"
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
