version: "3.9"

volumes:
  "grafana-storage":
  "elastic-data-01":

services:
  web:
    build:
      context: "node-services"
      dockerfile: "Dockerfile"
    ports:
      - "3030:3030"
      - "9209:9209"

  mongo:
    image: "mongo"
    ports:
      - 27017:27017

  mongo-exporter:
    image: "bitnami/mongodb-exporter"
    environment:
      MONGODB_URI: mongodb://mongo:27017
    ports:
      - "9216:9216"

  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.2"
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - elastic-data-01:/usr/share/elasticsearch/data

  elasticsearch-exporter:
    image: justwatch/elasticsearch_exporter:1.1.0
    command:
      - "--es.uri=http://es01:9200"
    restart: always
    ports:
      - "9114:9114"

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  node-exporter:
    image: "prom/node-exporter"
    ports:
      - "9100:9100"

  grafana:
    image: "grafana/grafana"
    environment:
      DS_PROMETHEUS: "Prometheus"
    volumes:
      - "grafana-storage:/var/lib/grafana"
      - "./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    ports:
      - "3000:3000"
